#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

languages = [
    ('Python', '.py'),
    ('JavaScript', '.js'),
    ('C++', '.cpp'),
    ('Java', '.java'),
]

slownik = {wartosc: klucz for (klucz, wartosc) in languages}
print(slownik)

soldiers = [
    {'name': 'Alice', 'rank': 'Private', 'service_years': 2},
    {'name': 'Bob', 'rank': 'Sergeant', 'service_years': 4},
    {'name': 'Charlie', 'rank': 'Sergeant', 'service_years': 6},
    {'name': 'David', 'rank': 'Lieutenant', 'service_years': 3},
    {'name': 'Eve', 'rank': 'Private', 'service_years': 1},
    {'name': 'Frank', 'rank': 'Lieutenant', 'service_years': 7},
]

jednostka = {soldier['rank']: sum(1 for soldie in soldiers if soldie['rank'] == soldier['rank']) for soldier in soldiers}
print(jednostka)

# tutaj jako wartosc zostalo wpisane list compreh bo potrzebne bylo ustalenie ile razy wystepuje dana ranga
# do tego celu jest suma jedynek gdy dla danego slownika w liscie jego rank jest taki jak dla klucza
