#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

wynik = [i for i in range(30) if i % 4 == 0]
print(wynik)

words = ['cat', 'dog', 'rabbit', 'hamster', 'parrot', 'raccoon']
words_r = [animal for animal in words if animal.startswith('r')]
print(words_r)

products = [
    {'name': 'T-shirt', 'price': 20, 'quantity': 10},
    {'name': 'Jeans', 'price': 50, 'quantity': 0},
    {'name': 'Sneakers', 'price': 80, 'quantity': 5},
    {'name': 'Hat', 'price': 15, 'quantity': 3},
    {'name': 'Backpack', 'price': 30, 'quantity': 7}
]

sa_na_magazynie = [produkt['name'] for produkt in products if produkt['quantity'] > 0]
print(sa_na_magazynie)