#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

lista = list(range(1,8))
print(lista)

slownik = {key: key*key for key in lista}
print(slownik)