#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

languages = [
    ('Python', '.py'),
    ('JavaScript', '.js'),
    ('C++', '.cpp'),
    ('Java', '.java'),
]

slownik = {wartosc: klucz for (klucz, wartosc) in languages}
print(slownik)

soldiers = [
    {'name': 'Alice', 'rank': 'Private', 'service_years': 2},
    {'name': 'Bob', 'rank': 'Sergeant', 'service_years': 4},
    {'name': 'Charlie', 'rank': 'Sergeant', 'service_years': 6},
    {'name': 'David', 'rank': 'Lieutenant', 'service_years': 3},
    {'name': 'Eve', 'rank': 'Private', 'service_years': 1},
    {'name': 'Frank', 'rank': 'Lieutenant', 'service_years': 7},
]

jednostka = {soldier['rank']: sum(1 for soldie in soldiers if soldie['rank'] == soldier['rank']) for soldier in soldiers}
print(jednostka)

# tutaj jako wartosc zostalo wpisane list compreh bo potrzebne bylo ustalenie ile razy wystepuje dana ranga
# do tego celu jest suma jedynek gdy dla danego slownika w liscie jego rank jest taki jak dla klucza

compounds = [
    {
        'name': 'Water',
        'atoms': ['H', 'O', 'H'],
    },
    {
        'name': 'Methane',
        'atoms': ['C', 'H', 'H', 'H', 'H'],
    },
    {
        'name': 'Ethanol',
        'atoms': ['C', 'H', 'O', 'H', 'H', 'C', 'H', 'H', 'H'],
    },
]

# Potrzebujesz stworzyć nowy słownik, który odwzorowuje każdy unikalny atom we wszystkich związkach na całkowitą
# liczbę wystąpień we wszystkich związkach.

compounds_number = {
    atom: sum(1 for compos in compounds if atom in compos['atoms'])       
    for compo in compounds                                              # zobacz jak zagniezdza sie petle zeby dobrac sie do elementow glebiej w strukturze
    for atom in compo['atoms']
    } 
print(compounds_number)

players = [
    {'name': 'Alice', 'position': 'Forward', 'goals': 15},
    {'name': 'Bob', 'position': 'Midfielder', 'goals': 7},
    {'name': 'Charlie', 'position': 'Defender', 'goals': 2},
    {'name': 'David', 'position': 'Goalkeeper', 'goals': 0},
    {'name': 'Eve', 'position': 'Forward', 'goals': 12},
    {'name': 'Frank', 'position': 'Midfielder', 'goals': 5},
]

# Potrzebujesz stworzyć nowy słownik, który odwzorowuje każdą pozycję na całkowitą liczbę bramek zdobytych przez graczy na tej pozycji.

bramki = {
    gracz['position']: sum(gracz['goals'] for grajek in players if grajek['position'] == gracz['position']) 
    for gracz in players
}
print(bramki)

