#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def check_nesting(struktura):
    for element in struktura:
        if isinstance(element, dict):
            print('To jest dict')
            return "Dict"
        elif isinstance(element, list):
            print('To jest list')
            return "List"
        
dictus = {1: 'jeden', 2: 'dwa', 3: {33: 'trzytrzy', 4: 'cztery'}}

x = check_nesting(dictus)
print(x)