#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    url = (
    'https://e-smartdata.teachable.com/p/sciezka-data-scientist'
    '-machine-learning-engineer'
    )
    lista = url.split('/')
    print(lista[-1].replace('-',' '))


if __name__ == '__main__': main()