#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    posts = [
        {
            'text': 'Lorem ipsum dolor sit amet, consectetur elit.',
            'author': 'John',
            'likes': 32,
        },
        {
            'text': 'Nulla facilisi. Duis eu aliquam libero.',
            'author': 'Jane',
            'likes': 87,
        },
        {
            'text': 'Vestibulum at ipsum ac diam sollicitudin tempor.',
            'author': 'Bob',
            'likes': 113,
        },
        {
            'text': 'Curabitur lobortis luctus velit, et scelerisque eu.',
            'author': 'Alice',
            'likes': 24,
        },
        {
            'text': 'Suspendisse nec enim rutrum, vehicula lectus ut.',
            'author': 'Mike',
            'likes': 99,
        },
    ]

    for i in posts:
        #print(i['likes'])
        if i['likes'] < 50:
            continue
        else:
            print(i['text'])




if __name__ == '__main__': main()