#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def longest(*args):
    max = 0
    for i in args:
        print(i)
        if len(i) > max:
            max = len(i)
    return max



def main():
    x = longest('asd' ,'ds' ,'ddddddd')
    print(x)
    
if __name__ == '__main__': main()