#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/quiz/5843380#overview

def main():
    print(bool(' '))
    print(bool(''))
    print(bool('1'))
    print(bool(['','']))
    #
    x = 3
    y = 5
    z = 0
    print(bool(x>y and z<y))

if __name__ == '__main__': main()