#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/quiz/5843380#overview

def main():
    slowo = 'asdasdasdasd'
    index = 0
    for i in range(len(slowo)):
        print(f'Index: {index} wartosc: {slowo[i]}')
        index += 1
    print('*'*30)
# u gory iterowanie po indexie i elementach ale latwiej zrobic to za pomoca enumerate
    for index, char in enumerate(slowo):
        print(f'Index: {index} wartosc: {char}')



if __name__ == '__main__': main()