#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    lista = list(range(10))
    print(*lista[1:])
    print(*lista[::2])
    lista2 = list(range(10, 110, 10))
    lista2.reverse()
    print(*lista2)

''' INNE ROZWIAZANIE PRZEZ FORa
for number in range(1, 10):
    print(number, end=' ')
 
print()
 
for number in range(0, 10, 2):
    print(number, end=' ')
 
print()
 
for number in range(100, 0, -10):
    print(number, end=' ')'''




if __name__ == '__main__': main()