#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview
''' Dla podanej listy wyprintuj tylko imiona skladajace sie ze znakow'''
def main():
 
    names = ['Jack', 'Leon', 'Alice', '32-3c', 'Bob']
    nielitery = ['0','1','2','3','4','5','6','7','8','9']
    for imie in names:
        licznik = 0
        for litera in imie:
            if litera in nielitery:
                #print('aaa')
                licznik += 1
        if licznik == 0:
            print('Hello', imie)

if __name__ == '__main__': main()