#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    products = [
    ('Shoes', 'Footwear', 150.00),
    ('T-shirt', 'Clothing', 50.00),
    ('Pants', 'Clothing', 100.00),
    ]
    
    for elementy_listy in products:
        if elementy_listy[1] == 'Clothing':
            print('The first product is: ',elementy_listy[0])
            break
if __name__ == '__main__': main()