#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course-dashboard-redirect/?course_id=2491660

def main():                                                                 #to co ja zrobilem
    fakt = 'python jest łatwy i przyjemny'
    lista = []
    for i in fakt:
        if i not in lista:
            lista.append(i)
    if len(lista) < 20:
        print('Mniej niż 20 unikalnych znaków.')
    else:
        print('Liczba unikalnych znaków jest większa lub równa 20.')

def sugerowane_rozwiazanie():                                               # to co sugerowal autor
    fakt = 'python jest łatwy i przyjemny'
    characters = list(fakt)                                                 #szybko zrobienie listy ze stringa
    length = len(set(characters))                                           #zrobienie zbioru z listy (zbior to unuikalne elementy)
    if length < 20:
        print("Mniej niż 20 unikalnych znaków.")
    else:
        print("Liczba unikalnych znaków jest większa lub równa 20.")

if __name__ == '__main__': main()
sugerowane_rozwiazanie()