#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course-dashboard-redirect/?course_id=2491660

def main():
    if bool(0) == True:
        print('aha0')
    else:
        print('Pffff')



if __name__ == '__main__': main()