#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <https://intel.udemy.com/course/programowanie-w-jezyku-python-od-a-do-z-cwiczenia/learn/quiz/5848768#overview>

def main():
    pi = 3.14
    r = 5
    print(f'The area of the circle is: {pi*r**2}')



if __name__ == '__main__': main()