#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <https://intel.udemy.com/course/programowanie-w-jezyku-python-od-a-do-z-cwiczenia/learn/quiz/5848768#overview>

def main():
    print(40*'=','\nautor: jannowak@poczta.com\n','data: 01-01-2021\n',40*'=',sep="")

   
    
if __name__ == '__main__': main()


