#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <may be some course, webpage etc> https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    print('Start')



if __name__ == '__main__': main()