#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview
import keyword

def main():
    imie = "seba"
    _imie = "ala"               # To jest traktowane jako wew zmienna pythona
    snake_case = imie + _imie   # snake_case typowo dla zmiennych i nazw funkcji, sa jeszcze camelCase, PascalCase i kebab-case

    STALA = 10                  # Stale przypisujemy wg notacji upper case
    print(keyword.kwlist)       # Pokaze jakich nazw nie wolno uzywac do zmiennych
    print('///'*30)
    print(dir(imie))            # dir pokaze dostepne metody dla tej klasy
    print('///'*30)
    print(dir(_imie))
    print('///'*30)
    print(dir(STALA))
    help(str.find)              # Wbudowany help do metod obiektow itp
    print(f'Stala is int: {isinstance(STALA, int)}')    # isinstance pokazuje czy dany obiekt jest danego typu
if __name__ == '__main__': main()