#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    a = 10
    print(f'Oryginalne a rowna sie {a} ')                           
    a %= 4
    print(f'Jak dla niego zrobimy % 4 to b rowna sie {a}')         # % modulo - czyli reszta z dzielenia
    a += 5     
    print(f'Jak dla niego zrobimy += 5 to c rowna sie {a}')        # x=x+5
    a -= 5
    print(f'Jak dla niego zrobimy -= 5 to d rowna sie {a}')        # x=x-5
    a *= 5
    print(f'Jak dla niego zrobimy *= 5 to e rowna sie {a}')        # x=x*5
    a //= 2
    print(f'Jak dla niego zrobimy //= 2 to f rowna sie {a}')       # Dzielenie z zaokragleniem do pelnych czesci
    a /= 2
    print(f'Jak dla niego zrobimy /= 5 to g rowna sie {a}')        # Dzielenie zwraca float wiec z przecinkiem, jesli chcemy pozbyc sie 0 po przecinku to uzyj // jak wyzej
    a **= 3
    print(f'Jak dla niego zrobimy **= 3 to h rowna sie {a}')       # Potegowanie

    # Notka, probowalem podac te wyrazenia od razu do printa ale on oczekuje wyrazen, a to sa operatory przypisania

if __name__ == '__main__': main()