#!/usr/bin/env python3
# Copyright SMAJKO

def main():
    x = 'Alekmakota'
    print(x)
    print(x[3:])    #pomin pierwsze 3
    print(x[:-3])   #pomin ostatnie 3
    print(x[:3])    #pokaz pierwsze 3
    print(x[-3:])   #pokaz ostatnie 3
    print(x[3:4])
    print(x[:4])
    print(x[::-1])  #pokaz od konca
    print(x[::-2])  #pokaz od konca co druga
    print(x[-2::])

    # there is also slice function to do the same 
    # a[slice(start, stop, step)]
    print(x[slice(3,0,1)])

if __name__ == '__main__': main()