#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <may be some course, webpage etc>

def main():
    print(40*'=','\nautor: jannowak@poczta.com\n','data: 01-01-2021\n',40*'=',sep="")

   
    
if __name__ == '__main__': main()