#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

passw = input("passw")

if len(passw) > 7:
    print("Great password there")
elif len(passw) == 7:
    print("Password is OK, but not too strong")
else:
    print("Your password is weak")