#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    slownik = {'Poland': 'Warsaw', 'Germany': 'Berlin', 'Austria': 'Vienna'}
    i = (slownik.keys(), slownik.values())
    print(slownik.get('Austria'))

if __name__ == '__main__': main()