#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    flights = [
        {
            'flight_num': 'AA123',
            'origin': 'LAX',
            'destination': 'JFK',
            'delay_minutes': 12,
        },
        {
            'flight_num': 'BB456',
            'origin': 'ORD',
            'destination': 'LAX',
            'delay_minutes': 0,
        },
        {
            'flight_num': 'CC789',
            'origin': 'JFK',
            'destination': 'ORD',
            'delay_minutes': 32,
        },
        {
            'flight_num': 'AA321',
            'origin': 'LAX',
            'destination': 'ORD',
            'delay_minutes': 6,
        },
        {
            'flight_num': 'BB654',
            'origin': 'JFK',
            'destination': 'LAX',
            'delay_minutes': 18,
        },
        {
            'flight_num': 'CC987',
            'origin': 'ORD',
            'destination': 'JFK',
            'delay_minutes': 24,
        },
    ]
    
    srednie_opoznienie = 0
    liczba_opoznionych = 0
    for i in flights:
        if i['delay_minutes'] > 0:
            srednie_opoznienie += i['delay_minutes']
            liczba_opoznionych += 1
    print(liczba_opoznionych)
    print(srednie_opoznienie)


if __name__ == '__main__': main()