#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview
"""
Najwazniejsze metody:
add()	Adds an element to the set
clear()	Removes all the elements from the set
discard()	Remove the specified item
intersection()	Returns a set, that is the intersection of two or more sets
pop()	Removes an element from the set
remove()	Removes the specified element
"""




def main():
    zbior = {'Ala', 'Misiu', 'Bubus'}          #set to zbior niepowtarzajacych sie, nieuporzadkowanych elementow
    print(zbior)
    print(type(zbior))
    ##################
    x = set('ssssadaddd')                      # funkcja set zbiera tylko unikalne iterowalne elementy
    print(x)
    y = 's' in x                               # czy s jest w zbioerze x? True or false
    print(y)
    ##################
    print(dir(set))
    zbior.add('Paulunda')
    print(zbior)
    zbior.discard('Bubus')
    print(zbior)
    



if __name__ == '__main__': main()