#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/quiz/5843242#overview
# Cwiczenie 19

def main():
    fruits = {'apple': 2, 'banana': 3, 'cherry': 5, 'orange': 1}
    print(f'Dictionary:',fruits)
    nowy_owoc = {'kiwi': 4}
    # albo tak:
    fruits['kiwi'] = 4
    #fruits.update(nowy_owoc)
    print(f'After adding:', fruits)
    fruits.pop('orange')
    # mozna jeszcze usuwac tak:
    # del fruits['orange']
    print(f'After deleting:', fruits)
    print(f'Keys:',fruits.keys())
    print(f'Values', fruits.values())

    
if __name__ == '__main__': main()