#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/quiz/5843242#overview
# Cwiczenie 20

def main():
    fruits = {'apple': 2, 'banana': 3}
    print('Dictionary before update:',fruits)
    fruits['apple'] = 4
    print('Dictionary after update:',fruits)
    fruits['kiwi']  = 1
    print('Dictionary after adding:',fruits)
    owoce = {'orange': 3, 'peach': 2}
    fruits.update(owoce)
    print('Dictionary after merging:',fruits)
    # Wszystkie te rzeczy mozna bylo tez zrobic w opraciu o fruits.update
    
if __name__ == '__main__': main()