#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <may be some course, webpage etc>

def main():
    lista = [1, 'cos', 2, 'egh', 4.5, True]             #milo ze mozna mieszac wszelakie typy danych
    lista2 = ['ala', 'ma', 'kota']
    for i in lista:
        print(type(i))
    polaczone = lista + lista2
    print(polaczone)
    gniazdko = [lista, lista2]
    print(gniazdko)
    gniazdko += 'a ja nie jestem lista'                 # dodaj kazdy znak jako element listy
    print(gniazdko)
    gniazdko += ['a ja jestem?']
    gniazdko += ['ffff', 'eggee']
    print(gniazdko)




if __name__ == '__main__': main()