#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <may be some course, webpage etc>

def main():
    # Poniżej zdefiniowane jest przybliżenie liczby pi
    pi = 3.1415926535

    # Używając formatowania f-string wydrukuj przybliżenie liczby pi
    # do drugiego miejsca po przecinku
    print(f'Przybliżenie liczby pi: {pi:.1}')
    
if __name__ == '__main__': main()