#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview
'''Odczytaj podany plik products.txt zawierający dane dotyczące produktów w sklepie internetowym:

smartfon,3000,10
laptop,5000,5
tablet,2000,12

Przedstaw te produkty w postaci listy słowników i przypisz do zmiennej products:

[{'name': 'smartfon', 'price': 3000.0, 'quantity': 10},
 {'name': 'laptop', 'price': 5000.0, 'quantity': 5},
 {'name': 'tablet', 'price': 2000.0, 'quantity': 12}]

Następnie wykorzystując pętlę for wydrukuj każdy produkt z listy products do konsoli tak jak poniżej.
Oczekiwany wynik:

{'name': 'smartfon', 'price': 3000.0, 'quantity': 10}
{'name': 'laptop', 'price': 5000.0, 'quantity': 5}
{'name': 'tablet', 'price': 2000.0, 'quantity': 12}'''

def main():

    FILE = 'C:\\github\\python_learning\\04_operacje_pliki\\products2.txt'
    products = []                           # lista slownikow bedzie
    with open(FILE, 'r') as file:
        for line in file:
            name, price, quantity = line.rstrip().split(',')
            products.append({'name': name,
                             'price': price,
                             'quantity': quantity})
    print(products)
    for item in products:
        print(item)


if __name__ == '__main__': main()