#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <https://intel.udemy.com/course/programowanie-w-jezyku-python-od-a-do-z-cwiczenia/learn/quiz/5848768#overview>

def main():
    item1 = 'Apples'
    quantity1 = 5
    price1 = 1.50

    item2 = 'Bananas'
    quantity2 = 7
    price2 = 0.99

    item3 = 'Oranges'
    quantity3 = 4
    price3 = 2.25

    print(3*('|'+10*'-') + '|')
    print(f'| {item1:<8} | {quantity1:<8} | {price1:^8.2f} |')
    print(f'| {item2:<8} | {quantity2:<8} | {price2:<8.2f} |')
    print(f'| {item3:<8} | {quantity3:<8} | {price3:>8.2f} |')




if __name__ == '__main__': main()