#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <https://intel.udemy.com/course/programowanie-w-jezyku-python-od-a-do-z-cwiczenia/learn/quiz/5848768#overview>

def main():
    filename = 'view.jpg'
    print(f'The file extension of the file \"{filename}\" is: {filename[-3:]}')



if __name__ == '__main__': main()