#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <https://intel.udemy.com/course/programowanie-w-jezyku-python-od-a-do-z-cwiczenia/learn/quiz/5848768#overview>

def main():
    string = '1 0 0 1 0 1'
    print(int((string[::2]), 2))



if __name__ == '__main__': main()