#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

try:
    total_value = float(input("Enter total value: "))
    value = float(input("Enter value: "))
    print(f'That is {value/total_value * 100}%')
    
except ValueError:
    print('You need to enter a number. Run the program again')

except ZeroDivisionError:
    print('Your total value cannot be zero.')