#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

try:
    x = 1 / 0
    print(x)
except:
    print('Ups')

##########################################

try:
    x = 1 / 0
    print(x)
except ZeroDivisionError:
    print('nie wolno')

##########################################
    
try:
    with open('plik_ktorego_nie_ma.txt', 'r') as file:
        for line in file:
            print(line)
except FileNotFoundError:
    print('Nie ma takiego pliku')

##########################################
    
# mozna tez podnosic swoje bledy  
#if 1 > 0:
#    raise ValueError('ale prawdziwe')

##########################################

def divide(x,y):
    try:
        return x / y
    except ZeroDivisionError:
        print('Niedozwolone dzielenie przez 0')
x = divide(2,3)
y = divide(3,0)

##########################################

def test_sum():                                                 # assertem mozna sprawdzic sobie wczesniej czy nie mamy jakiegos bledu
    assert sum([1,2,3]) == 711, 'Powinno byc 6'

if __name__ == '__main__':
    test_sum()