#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def main():
    stocks = [(1, 3), (4, 1), (4, 2), (0, 7)]
    print(sorted(stocks, key=lambda element: element[1]))

if __name__ == '__main__': main()