#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def calculate_time(h, g=9.80665):
    t = (2 * h / g) ** 0.5
    return t
    
  
time = calculate_time(100)
print(time)