#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def argsy(*args):
    print(args)                         # to zwroci liste elementow podanych do wywolania funkcji

def kwargsy(**kwargs):
    print(kwargs)                       # tutaj kwargsy moga miec jedynie postac slownika

def argsyikwargsy(*args, **kwargs):
    print(args)                         # lista argumentow
    print(kwargs)                       # slownik zmiennych i ich wartosci
    #mozna to wykorzystac:
    print(sum(args))
    print(kwargs.items())
    print(kwargs.keys())
    print(kwargs.values())
    print(len(kwargs))
    return kwargs

def main():

    argsy(1,2,3,4,5)
    #kwargsy(1,2,3,4,5)   
    kwargsy(**{'1': 'jeden'})
    argsyikwargsy(1,2,3, a=10, b=20)
    f = argsyikwargsy(1,2,3, a=10, b=20)
    print(f)


if __name__ == '__main__': main()