#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview

def func1():
    """ This is a docstring describing what the function is used for
    It is very usefull to have this info here. General format is what
    is taken as input and what it returns """
    print('Elo')

def func2(x,y):
    print('x={} y={}'.format(x,y))

def func3(x,y=10):                      # defaultowe argumenty zawsze po niedefaultowych, wywoalania tej funkcji tak samo
    print('x={} y={}'.format(x,y))

def srednia(x,y,z):
    return (x+y+z)/3


def main():
    func1()
    func2(1,3)
    func3(5)                            # jesli jeden jest domyslny to nie trzeba podawac drugiego
    func3(5,8)                          # jesli jednak podamy drugi to on nadpisuje domyslny z definicji funkcji
    func3(y=11, x=4)                    # tez bedzie dzialac jesli jako argumenty wpiszemy to co jest w def funkcji
    print(srednia(1,2,3))               # funkcja musi cos zwracac, te wyzej z printami nic nie zwracaja sa tylko sekwencja polecen
    x = srednia(3,4,5)
    print(type(x))

if __name__ == '__main__': main()