#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://intel.udemy.com/course/programowanie-w-jezyku-python/learn/lecture/15723394?start=0#overview
'''
Podana jest poniższa lista:
items = [(3, 4), (2, 5), (1, 4), (6, 1)]
Posortuj listę według rosnącej sumy kwadratów liczb podanych w obiektach typu tuple. Użyj metody list.sort() oraz wyrażenia lambda. 
W odpowiedzi wydrukuj listę do konsoli.
Oczekiwany wynik:
[(1, 4), (3, 4), (2, 5), (6, 1)]'''

def main():
    items = [(3, 4), (2, 5), (1, 4), (6, 1)]
    print(list(map(lambda x: x[0]**2 + x[1]**2, items)))
    x = sorted(items, key=lambda y: y[0]**2 + y[1]**2)
    print(x)

if __name__ == '__main__': main()