#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://learning.oreilly.com/library/view/python-workout/9781617295508/

'''Exercise 27
In this exercise, we’re going to create a password-generation function. Actually, we’re going to create a factory for password-generation functions. 
That is, I might need to generate a large number of passwords, all of which use the same set of characters. (You know how it is. Some applications 
require a mix of capital letters, lowercase letters, numbers, and symbols; whereas others require that you only use letters; and still others allow 
both letters and digits.) You’ll thus call the function create_password _generator with a string. That string will return a function, which itself 
takes an integer argument. Calling this function will return a password of the specified length, using the string from which it was created

'''
words = 'this is a bunch of words'.split()
def is_a_long_word(one_word):
    return True if len(one_word) > 4 else False
 
x = map(is_a_long_word, words)
print(' '.join(x))  





