#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://learning.oreilly.com/library/view/python-workout/9781617295508/

'''Exercise 13
For this exercise, write a Python function, format_sort_records, that takes the PEOPLE list and returns a formatted string that looks like the following:

Trump      Donald      7.85
Putin      Vladimir    3.63
Xi         Jinping    10.60
'''

PEOPLE = [('Donald', 'Trump', 7.85),
          ('Vladimir', 'Putin', 3.626),
          ('Jinping', 'Xi', 10.603)]

def format_sort_records(lista):
    wynik = []
    print(lista)
    wynik = sorted(lista, key = lambda tup: tup[1])
    print(wynik)
    for person in wynik:
        print('{1:10} {0:10} {2:5.2f}'.format(person[1], person[0], person[2]))


format_sort_records(PEOPLE)