#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://learning.oreilly.com/library/view/python-workout/9781617295508/

'''Exercise 14
You should then write a function, restaurant, that asks the user to enter an order:

If the user enters the name of a dish on the menu, the program prints the price and the running total. It then asks the user again for their order.

If the user enters the name of a dish not on the menu, the program scolds the user (mildly). It then asks the user again for their order.

If the user enters an empty string, the program stops prompting and prints the total amount.

For example, a session with the user might look like this:

Order: sandwich
sandwich costs 10, total is 10
Order: tea
tea costs 7, total is 17
Order: elephant
Sorry, we are fresh out of elephant today.
Order: <enter>
Your total is 17
'''

MENU = {'sandwich': 10, 'tea': 7, 'salad': 9}

def restaurant():
    sum = 0
    while True:
        x = input("Podaj danie: ").strip()
        if not x or x.strip() == '':               # jak nie poda nic albo spacje tylko to wyjdz
            break

        if x in MENU:
            sum += MENU[x]
            print("Suma zamowienia:", sum)
        else:
            print('Nie mamy', x)

        


restaurant()