#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://learning.oreilly.com/library/view/python-workout/9781617295508/

'''Exercise 15
Specifically, write a function, get_rainfall, that tracks rainfall in a number of cities. Users of your program will enter the name of a 
city; if the city name is blank, then the function prints a report (which I’ll describe) before exiting.
'''

def rainfall():
    rainfall_dict = {}
    while True:
        miasto = input("Podaj miasto: ").strip()
        if not miasto or miasto.strip() == '':               # jak nie poda nic albo spacje tylko to wyjdz
            break
        
        if miasto:
            mm = int(input("Podaj ile mm wody: "))
            rainfall_dict[miasto] = rainfall_dict.get(miasto, 0) + mm       #get tutaj sprawdza czy w slowniku mamy juz miasto (i jego wartosc) jesli nie ma to zwraca 0

    for miasto, mm in rainfall_dict.items():
        print(f'{miasto}: {mm}')

        


rainfall()