#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://learning.oreilly.com/library/view/python-workout/9781617295508/

'''Exercise 18
Print last line from a file
'''

import os
plik = '01_guessing_game'

desired_path = os.path.dirname(__file__) + '\\' + plik      # wychodzi na to ze __file__ to plik pythonowy jaki piszemy

def lastline(file):
    lastline = ''
    for line in open(file):
        lastline = line
    return lastline


print(lastline(desired_path))

"""
Na potrzeby testow mozna skorzystac z fakowych plikow jakie dostarcza biblioteka io

import io
fakefile = StringIO('''
linijka1
linijka2
linijka3
''')

"""