#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://learning.oreilly.com/library/view/python-workout/9781617295508/

'''Exercise 26
To jest hybryda oryginalu, pokazuje jak ladnie mozna wykorzystac funkcje w slowniku

'''


def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def kalkulator(do_policzenia):
    operacje = {'+': add, '-': sub}                         # tutaj mozna nawet skorzystac z gotowca importujac modul operator i dajac tu od razu funkcje jako wartosci slownika
                                                            # czyli mielibysmy tutaj wtedy tak: operacje = {'+': operator.add, '-': operator.sub}
    operator, liczba_pierwsza, liczba_druga = do_policzenia.split()
    liczba_pierwsza = int(liczba_pierwsza)
    liczba_druga = int(liczba_druga)

    return operacje[operator](liczba_pierwsza, liczba_druga)

print(kalkulator('+ 1 2'))





