#!/usr/bin/env python3
# Copyright SMAJKO

#Source: https://learning.oreilly.com/library/view/python-workout/9781617295508/

'''Exercise 28
For this exercise, write a function (join_numbers) that takes a range of integers. The function should return those numbers as a string, with commas 
between the numbers. That is, given range(15) as input, the function should return this string:

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14

'''
import random

def join_numbers(n):
    string = [''.join(str(number)) for number in range(n)]
    return ','.join(string)

x = join_numbers(11)
print(x)

'''
def join_numbers(numbers):
    return ','.join(str(number) for number in numbers)
'''



