#!/usr/bin/env python3
# Copyright SMAJKO

#Source: <https://intel.udemy.com/course/programowanie-w-jezyku-python-od-a-do-z-cwiczenia/learn/quiz/5848768#overview>

def main():
    input_text = 'Python Course'
    print(f'The reversed text of "{input_text}" is: {input_text[::-1]}')



if __name__ == '__main__': main()